# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build & Deploy

on:
  # 支持手动触发构建
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK"
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
          server-id: carm-repo
          server-username: MAVEN_USERNAME
          server-password: MAVEN_TOKEN

      - name: "Package"
        run: mvn -B -Pprivate deploy --file pom.xml
        env:
          MAVEN_USERNAME: "carm"
          MAVEN_TOKEN: ${{secrets.MAVEN_PASSWORD}}

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: "**/target/"
          retention-days: 1 # 仅保留1天。

      - name: "Upload assets"
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: ".asset/"
          retention-days: 5